definitions:
  steps:
  - step: &pytest
        name: Run tests
        runtime:
          cloud:
            arch: arm
        image:
          name: "397662812780.dkr.ecr.eu-west-1.amazonaws.com/microservice-pdftransformation:latest"
          aws:
            oidc-role: "arn:aws:iam::397662812780:role/bitbucket_pipeline_pdftransformation"
        oidc: true
        script:
          - echo "execute pytest"
          - poetry run pytest tests --disable-warnings
pipelines:
  custom: # trigger manually
    run-tests:
      - step: *pytest
  pull-requests: # this runs when pull request is created
    "**": # this runs as default for any branch not elsewhere defined
      - parallel:
        - step: *pytest
